#pragma once

#include "Util/Debug.hpp"

#define REPORT_SUBSCRIBER_COUNT(LABEL, PUBLISHER) BURP_DEBUG_INFO(LABEL ": subscribers: %u%s", PUBLISHER->getSubscriberCount(), PUBLISHER->isOverSubscribed() ? " - OVERSUBSCRIBED" : "")

#ifndef BURP_DIMMER_LIGHT_SUBSCRIBERS
#define BURP_DIMMER_LIGHT_SUBSCRIBERS 5
#endif

#ifndef BURP_DIMMER_CONFIG_SUBSCRIBERS
#define BURP_DIMMER_CONFIG_SUBSCRIBERS 5
#endif

#ifndef BURP_DIMMER_CONFIG_NETWORK_SUBSCRIBERS
#define BURP_DIMMER_CONFIG_NETWORK_SUBSCRIBERS 5
#endif

#ifndef BURP_DIMMER_CONFIG_NETWORK_STATION_SUBSCRIBERS
#define BURP_DIMMER_CONFIG_NETWORK_STATION_SUBSCRIBERS 5
#endif

#ifndef BURP_DIMMER_CONFIG_NETWORK_MANAGER_SUBSCRIBERS
#define BURP_DIMMER_CONFIG_NETWORK_MANAGER_SUBSCRIBERS 5
#endif

#ifndef BURP_DIMMER_CONFIG_NETWORK_ACCESS_POINT_SUBSCRIBERS
#define BURP_DIMMER_CONFIG_NETWORK_ACCESS_POINT_SUBSCRIBERS 5
#endif

#ifndef BURP_DIMMER_CONFIG_LIGHT_SUBSCRIBERS
#define BURP_DIMMER_CONFIG_LIGHT_SUBSCRIBERS 5
#endif

