#pragma once

#include <Arduino.h>

#ifndef BURP_DIMMER_LIGHT_PIN
#define BURP_DIMMER_LIGHT_PIN D1
#endif

#ifndef BURP_DIMMER_LIGHT_ROTARY_ENCODER_PIN_1
#define BURP_DIMMER_LIGHT_ROTARY_ENCODER_PIN_1 D5
#endif

#ifndef BURP_DIMMER_LIGHT_ROTARY_ENCODER_PIN_2
#define BURP_DIMMER_LIGHT_ROTARY_ENCODER_PIN_2 D6
#endif

#ifndef BURP_DIMMER_LIGHT_BUTTON_PIN
#define BURP_DIMMER_LIGHT_BUTTON_PIN D7
#endif

#ifndef BURP_DIMMER_DEBOUNCE_DELAY
#define BURP_DIMMER_DEBOUNCE_DELAY 20
#endif
