#pragma once

#include <Redux/Action.hpp>

namespace Config {

  enum class ActionType {
    NETWORK_MANAGER_DESERIALIZE,
    NETWORK_MANAGER_SET_ACCESS_POINT_TIMEOUT,
    NETWORK_MANAGER_NEXT_PERM_MODE,
    NETWORK_MANAGER_SET_PERM_MODE,
    NETWORK_MANAGER_SET_TEMP_MODE,
    NETWORK_STATION_DESERIALIZE,
    NETWORK_ACCESS_POINT_DESERIALIZE,
    LIGHT_DESERIALIZE
  };

  using Action = Redux::Action<ActionType>;

}
